import type { Metadata } from "next";
import "./globals.css";

import { MyProvider } from "./context/store";
import Navbar from "./component/Navbar";
import Modal from "./component/Modal";

export const metadata: Metadata = {
  title: "Frontend Mentor | Rock, Paper, Scissors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MyProvider>
        <body>
          <Modal />
          <main className="py-4">
            <Navbar />
            <div className="mx-auto mt-24 w-10/12 max-w-[1000px] md:mt-48">
              {children}
            </div>
          </main>
        </body>
      </MyProvider>
    </html>
  );
}
